# Continuous Deployment on every push to master.

name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to GCR
      uses: ThomFree/action_build_push_gcr@1.0
      with:
        image: gcr.io/covision19/api
        project: covision19
        region: us-west-1
        service key: ${{ secrets.GCLOUD_AUTH }}
