# Continuous Deployment on every push to master.

name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build, Push and Deploy service to Google Cloud Run
      uses: ThomFree/action-build-cloud-run@1.1
      with:
        image: gcr.io/covision19/api
        service: api-runner
        project: covision19
        region: us-west1
        service key: ${{ secrets.GCLOUD_AUTH }}
