# Continuous Deployment on every push to master.

name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cloud Run with docker build and push to GCR
      uses: passionkind/action-cloud-run@1.5
      with:
        # Set to true to check if working_directory has changes since the previous commit
        check_if_changed: false
        # Directory where the Dockerfile is to be found
        working_directory: ./ 
        # Cloud run service name
        service_name: api-runner
        # GCP service key with storage and run permissions
        gcp_service_key: ${{ secrets.DOCKER_DEPLOY_PWD }}
        # GCP project
        project: covision19
        # GCP Registry (e.g. 'eu.gcr.io')
        registry: gcr.io
