# Continuous Deployment on every push to master.

name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to GCR
      uses: ThomFree/action_build_push_gcr@1.0
      with:
        image: gcr.io/covision19/api
        project: covision19
        region: us-west-1
        service key: ${{ secrets.GCLOUD_AUTH }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: |
          echo "${{ secrets.DEPLOY_SSHKEY }}" > private.key
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key echo "${{ secrets.GCLOUD_AUTH }}" | base64 --decode > gcloud.json
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key gcloud auth activate-service-account --key-file=gcloud.json --project covision19
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key gcloud auth configure-docker
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key docker pull gcr.io/covision19/api
      - name: Run docker image
        run: |
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key docker stop gcr.io/covision19/api
          ssh deploy-bot@covision19.thedoux.fr -i ./private.key docker run gcr.io/covision19/api -p 8080:8080 --env PORT=8080
